services:
   pps-db-master:
      container_name: pps-db-master
      image: bitnami/postgresql:latest
      environment:
         - POSTGRESQL_PGAUDIT_LOG=READ,WRITE
         - POSTGRESQL_LOG_HOSTNAME=true
         - POSTGRESQL_REPLICATION_MODE=master
         - POSTGRESQL_REPLICATION_USER=replicator
         - POSTGRESQL_REPLICATION_PASSWORD=KQYsG4Hi201ajyEzOSGzr4MVfw==
         - POSTGRESQL_USERNAME=postgres
         - POSTGRESQL_PASSWORD=KQYsG4Hi201ajyEzOSGzr4MVfw==
         - ALLOW_EMPTY_PASSWORD=yes
      ports:
         - "1000:5432"
      volumes:
         - ./pgdata/master:/bitnami/postgresql
      networks:
         - pps-network

   pps-db-slave1:
      container_name: pps-db-slave1
      image: bitnami/postgresql:latest
      environment:
         - POSTGRESQL_USERNAME=postgres
         - POSTGRESQL_PASSWORD=KQYsG4Hi201ajyEzOSGzr4MVfw==
         - POSTGRESQL_MASTER_HOST=pps-db-master
         - POSTGRESQL_PGAUDIT_LOG=READ,WRITE
         - POSTGRESQL_LOG_HOSTNAME=true
         - POSTGRESQL_REPLICATION_MODE=slave
         - POSTGRESQL_REPLICATION_USER=replicator
         - POSTGRESQL_REPLICATION_PASSWORD=KQYsG4Hi201ajyEzOSGzr4MVfw==
         - POSTGRESQL_MASTER_PORT_NUMBER=5432
      ports:
         - "1001:5432"
      volumes:
         - ./pgdata/slave1:/bitnami/postgresql
      networks:
         - pps-network

   pps-pgpool:
      image: bitnami/pgpool:latest
      container_name: pps-pgpool
      environment:
         - PGPOOL_BACKEND_NODES=0:pps-db-master:5432,1:pps-db-slave1:5432
         - PGPOOL_SR_CHECK_USER=replicator
         - PGPOOL_SR_CHECK_PASSWORD=KQYsG4Hi201ajyEzOSGzr4MVfw==
         - PGPOOL_POSTGRES_USERNAME=postgres
         - PGPOOL_POSTGRES_PASSWORD=KQYsG4Hi201ajyEzOSGzr4MVfw==
         - PGPOOL_ADMIN_USERNAME=admin
         - PGPOOL_ADMIN_PASSWORD=KQYsG4Hi201ajyEzOSGzr4MVfw==
         - ALLOW_EMPTY_PASSWORD=yes
      #volumes:
      #- ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      ports:
         - "1999:5432"
      networks:
         - pps-network

   pps-redis:
      image: redis:alpine
      container_name: pps-redis
      ports:
         - 8010:6379
      networks:
         - pps-network
      restart: always

   pps-login:
      container_name: pps-login
      build:
         context: ./tugas-akhir/login
         dockerfile: ./Dockerfile
      ports:
         - 8013:80
      volumes:
         - ./tugas-akhir/login:/var/www/html
      networks:
         - pps-network
      restart: always

   pps-akademik:
      container_name: pps-akademik
      build:
         context: ./tugas-akhir/akademik
         dockerfile: ./Dockerfile
      ports:
         - 8015:80
      volumes:
         - ./tugas-akhir/akademik:/var/www/html
      networks:
         - pps-network
      restart: always

   pps-mahasiswa:
      container_name: pps-mahasiswa
      build:
         context: ./tugas-akhir/mahasiswa
         dockerfile: ./Dockerfile
      ports:
         - 8011:80
      volumes:
         - ./tugas-akhir/mahasiswa:/var/www/html
      networks:
         - pps-network
      restart: always

   pps-admin:
      container_name: pps-admin
      build:
         context: ./tugas-akhir/admin
         dockerfile: ./Dockerfile
      ports:
         - 8014:80
      volumes:
         - ./tugas-akhir/admin:/var/www/html
      networks:
         - pps-network
      restart: always

   pps-dosen:
      container_name: pps-dosen
      build:
         context: ./tugas-akhir/dosen
         dockerfile: ./Dockerfile
      ports:
         - 8017:80
      volumes:
         - ./tugas-akhir/dosen:/var/www/html
      networks:
         - pps-network
      restart: always

networks:
   pps-network:
      external: true
